### PR TITLE
Color pal

### PR DESCRIPTION
**Pull request by michaelcurry1123**
**What changes are proposed in this pull request?**
Changed several color functions, created some new ones and removed ones that didn't need to be supported. `scale_color_*` functions are still available but should be removed eventually and `set_gnomer_palette()` should be used instead.

**If there is an GitHub issue associated with this pull request, please provide link.**

#211  #230 
--------------------------------------------------------------------------------

  Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded.
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
 - [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cbioportalR (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR

### CODE REVIEW

**Comment by karissawhiting** [comment]
@michaelcurry1123 could you add an example of using these palettes in the vignette?

**Comment by michaelcurry1123** [comment]
@karissawhiting yes I can, did you want to merge the vignette first and then I can merge main into this branch and work from there?

**Comment by karissawhiting** [comment]
@michaelcurry1123 Yes! Just merged vignette changes so all set to add. Thanks!

**Comment by michaelcurry1123** [comment]
@karissawhiting made my changes and added to the vignette

**Comment by karissawhiting** [comment]
Can we make `plot_col = TRUE` by default? Will this mess up plots? I don't think it will but let's double check. If not we can set this as the default.

**Comment by karissawhiting** [comment]
Add a color blind palette?

**Comment by karissawhiting** [comment]
Add a color blind palette? #231

**Comment by karissawhiting** [comment]
> Can we make `plot_col = TRUE` by default? Will this mess up plots? I don't think it will but let's double check. If not we can set this as the default.

@michaelcurry1123 and I decided not to and to leave as is. We can add back print method in the future if we want.

**Pull request merged**
