### PR TITLE
Fusion format function

### PR DESCRIPTION
**Pull request by hfuchs5**
**What changes are proposed in this pull request?**
A function to take long fusion format and make it wide. It also removes any repeated observations due to alphabetical listing of fusion (ex: listed geneA-geneB in one version but geneB-geneA in another). This is needed for GENIE data.

**If there is an GitHub issue associated with this pull request, please provide link.**
#229 

--------------------------------------------------------------------------------

  Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded.
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
 - [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cbioportalR (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR

### CODE REVIEW

**Comment by karissawhiting** [comment]
@hfuchs5 I've been thinking about this more, and I'm wondering if we can use the `hugo_symbol` column to generate the `site1` and `site2` columns instead of the fusions column. If this works out it will save us a lot of hardcoding and help keep the function generalizable to future data sets, but I'm not sure this will correctly catch the edge cases. Here's a little mockup of what I'm thinking:

```r

# Test Data ---------------------------------------------------------------

fusions <-  gnomeR::sv_long %>%
  rename_columns()

# make fake 3 gene fusion to test
fusions[1, 'fusion'] <- "OXSR1-MYD88-APC fusion"
fusions[2, ] <- fusions[1, ]
fusions[3, ] <- fusions[1, ]
fusions[2, "hugo_symbol"] <- "OXSR1"
fusions[3, "hugo_symbol"] <- "APC"


# Reformat Fusion ---------------------------------------------------------

# Create an ID for each unique fusion
fus <- fusions %>%
  group_by(sample_id, fusion) %>%
  mutate(fusion_id = cur_group_id()) %>%
  mutate(hugo_index = 1:n())


# Pivot Way ----------
fus_pivot <- fus %>%
  select(hugo_symbol, hugo_index, sample_id, fusion, fusion_id) %>%
  mutate(new_names = paste0(paste0("site", hugo_index), "hugo_symbol")) %>%
  pivot_wider(id_cols = c(fusion_id, fusion),
              names_from = new_names,
              values_from = hugo_symbol )
```

Let me know if I'm missing anything or you spot an example this may not work on. 

If that doesn't work, I'm down to go with a more regex-based solution similar to what you've code. Trying to think of a way we can validate gene names versus non gene name sections of the 'fusion' column without having to hard code every exception but having trouble....
```r
# Create an ID for each unique fusion
fus <- fusions %>%
  group_by(sample_id, fusion) %>%
  mutate(fusion_id = cur_group_id()) %>%
  mutate(hugo_index = 1:n())



# Regex Version -------------

fus_reg <- fus %>%
  mutate(fusion = str_trim(fusion)) %>%
  # ensure there are no spaces between hyphen and next letter (problem with - Archer)
  mutate(fusion = str_replace_all(fusion, "- ", "-")) %>%
  separate(fusion, into = c("site1hugo_symbol",
                            "site2hugo_symbol",
                            "site3hugo_symbol",
                            "site4hugo_symbol"),
           remove = FALSE)
#<Need to replace intragenic/archer/intergenic etc here!>
```

This is so tricky, let me know your thoughts!

**Comment by hfuchs5** [comment]
So far I haven't seen a fusion that is actually three genes like your example. They are all a gene name with a suffix. For example:
"BRAF-LINC-PINT" looks like it should be 3 hugo_symbols, but based on the cbioportal datasets, "LINC-PINT" is one gene. This gets complicated if/when the order switches to "LINC-PINT-BRAF" in the fusion column because a regex to split at the first hypen would incorrectly group PINT and BRAF as one.

But, I think that we could use the regex version if we separate the type of fusion name from the fusion column (ex: "APC intragenic" or ""BRAF-LINC-PINT fusion" should only have one space, so we could pull the additional words into another column.

When I use the RegExr which is Java but simiar to R, the works for fusion/fusion - Archer/intergenic/etc ^[A-Za-z]+\B[A-Za-z0-9]\b(?:\W+)?(?:[A-Za-z]+)?

But when I copy it into R it doesn't work exactly right. Need to keep looking.

```
sv_long %>%
                        separate_wider_regex(fusion,
                                      patterns = c(site1 = "\\w+", "-", site2 = "\\w+", "  *", fusion_name = "^[A-Za-z]+\\B[A-Za-z0-9]\\b(?:\\W+)?(?:[A-Za-z]+)?")
                                    )

```

**Comment by karissawhiting** [comment]
@hfuchs5 What does "BRAF-LINC-PINT" look like in terms of the hugo symbol column? would the first way that just uses that col work for that one?

**Comment by karissawhiting** [comment]
@hfuchs5 Took another stab at simplifying this and came up with the following. Does this cover the edge cases?

```r 

library(genieBPC)

# Data Example ------------------------------------------------------------
set_synapse_credentials()

ex1 <- pull_data_synapse(
  cohort = c("NSCLC"),
  version = c("v2.0-public")
)

fusions <- ex1$NSCLC_v2.0$fusions

# examples to be checked
int = c(
  "NPHP3-AS1-STAG1",
  "STAG1-NPHP3-AS1",
  "RICTOR-NIPBL-AS1",
  "PMF1-BGLAP-RIT1",
  "U2AF1-MCM3AP-AS1",
  "MCM3AP-AS1-U2AF1",
  "MIR365-2-NF1",
  "FAT1-F11-AS1",
  "TCEB1-DLGAP1-AS5",
  "TAP2-HLA-DOB",
  "BIVM-ERCC5-GLUD1",
  "GLUD1-BIVM-ERCC5",
  "CREBBP-AATK-AS1",
  "CDKN2B-AS1-CDKN2A",
  "ETV6-PRH1-PRR4",
  "KMT2A-TMPRSS4-AS1",
  "TMPRSS4-AS1-KMT2A",
  "RNU6-19P-ETV6",
  "RAD21-C8orf37-AS1",
  "BRWD1-IT2-TMPRSS2",
  "TMPRSS2-BRWD1-IT2",
  "CTD-2151A2.1-DROSH",
  "FOXA1-NKX2-8",
  "BRAF-LINC-PINT",
  "MIR365-2-NF1",
  "SOX2-OT-SOX2")


fusions$Fusion[1:26] <- int

# should we check against hugo symbol colums?
# should we return original fusion columns?


# Function ----------------------------------------------------------------

reformat_fusion <- function(fusions) {

  # Checks --------------------------------------------------------------------
  if (!is.data.frame(fusions)) {
    cli::cli_abort("{.code fusion} must be a data.frame")
  }

  fusions <- rename_columns(fusions)
  .check_required_cols(fusions, c("fusion", "sample_id", "hugo_symbol"))

  # Clean Strings -------------------------------------------------------------
  fusions_sep <- fusions %>%
    mutate(
      # remove leading space in fusion var
      fusion = str_trim(.data$fusion),
      # ensure there are no spaces between hyphen and next letter (problem with - Archer)
      fusion = str_replace_all(fusion, "- ", "-"),
      # remove "Archer"
      fusion = str_remove_all(fusion, "-Archer"))


  # Replace Known Hugo Exceptions -------------------------------------------

  # check for cells with more than one hyphen
  any_double_dash <- (str_count(fusions_sep$hugo_symbol, "-") == 1 |
                        str_count(fusions_sep$fusion, "-") > 1)

  # list of known genes with a hyphen to replace with underscore in data
  exceptions <- c(
    # generalized edits
    "-AS" = "_AS",
    "HLA-" = "HLA_",
    "NKX2-" = "NKX2_",

    # specific edits
    "SOX2-OT"= "SOXOT",
    "MIR365-2"= "MIR365_2",
    "LINC-PINT"= "LINC_PINT",
    "NKX2-8"= "NKX2_8",
    "PMF1-BGLAP"= "PMF1_BGLAP",
    "BIVM-ERCC5"= "BIVM_ERCC5",
    "PRH1-PRR4"= "PRH1_PRR4",
    "RNU6-19P"= "RNU6_19P",
    "BRWD1-IT2"= "BRWD1_IT2",
    "CTD-2151A2.1"= "CTD_2151A2.1")

  fusions_sep$fusion[any_double_dash] <- str_replace_all(
    fusions_sep$fusion[any_double_dash], exceptions)


  # Split Into Hugo Symbol 1 & 2  ---------------------------------------------

  # only retain string before and after first dash, then remove intergenic/intragenic
  fusions_sep <- fusions_sep %>%
    mutate(fusion_orig = fusion) %>%
    mutate(
      fusion = str_extract(fusion, "[[:alnum:]_]+-[[:alnum:]_]+")) %>%
    mutate(
      fusion = str_remove_all(fusion,
                              "-INTERGENIC|-intergenic|-INTRAGENIC|-intragenic"))

  # split into hugo symbol columns
  fusions_sep <- fusions_sep %>%
    separate(fusion, into = paste0("site", 1:4, "hugo_symbol"),
             sep = "-",
             remove = FALSE,
             extra = "drop",
             fill = "right")


  # find any remaining hugo_symbols that have 2 hyphens
  any_gr3 <- which(!is.na(fusions_sep$site3hugo_symbol) | !is.na(fusions_sep$site4hugo_symbol))

  if(length(any_gr3) > 0) {
    cli::cli_abort(c("Unable to process the following fusions in the 'fusion'",
                     "col: {fusions_sep$fusion[any_gr3]}. Please reformat these as `HUGO1-HUGO2`. Hugo names cannot have '-' only '_'"
      ))
  }

  # filters out any mistakes because this should never be in the first site position
  fusions_sep <- fusions_sep %>%
    select(
      "sample_id", "hugo_symbol", "site1hugo_symbol", "site2hugo_symbol", "fusion"
    ) %>%
    filter(!(.data$site1hugo_symbol %in% c("repeat", "insufficient")))


  # There are cases where site 1 and 2 were flipped for a sample_id and listed x2
  # ex: TP53-APC vs APC-TP53
  # Here we sort each hugo alphabetically, then paste
  fusions_sep <- fusions_sep %>%
    mutate(fusions_ordered = purrr::pmap_chr(list(site1hugo_symbol, site2hugo_symbol),
                                             ~paste0(sort(c(.x, .y)), collapse = "-")))

  fusions_unq <- fusions_sep %>%
    select(sample_id, fusions_ordered) %>%
    distinct()

  fusions_unq <- fusions_unq %>%
    separate(fusions_ordered, sep = "-",
             into = c("site1hugo_symbol", "site2hugo_symbol"),
             extra = "drop",
             fill = "right")

  fusions_unq
}

# Example -----------------------------------------------------------------

z <- reformat_fusion(fusions)


```

**Comment by michaelcurry1123** [comment]
I lazily took a stab at it, this is a similar approach Karissa took. The sample ids and pairs in the code below match the reformat_fusion function. 

```
fusionsx <- sv_long %>% 
            separate(fusion, sep = " ", into = c("pair","type"),
                     remove = FALSE) %>% 
            mutate(pair2 = sapply(lapply(strsplit(c(.data$pair), '-'), sort), 
                                  function(x){paste(x,collapse = "-")})) %>% 
            group_by(sample_id, pair2) %>% 
            filter(row_number()==1) %>% 
            ungroup() %>% 
            select(-pair2, pair, type)
```

**Comment by michaelcurry1123** [comment]
@karissawhiting  I see in your code your replace hyphens with underscores with genes that have hyphens in their name. Is this necessary?  In the example below if you assume KPR is one gene and ax-ng is another you can still split and sort and end up with the same ordering and de-dup on this column (and then remove it bc it is nonsense because the order is ax-kpr-ng). Or is this solution too lazy? 
```
 a <- c("kpr-ax-ng")
 b <- c("ax-ng-kpr")
 sapply(lapply(strsplit(c(a,b), '-'), sort), 
        function(x){paste(x,collapse = "-")})
```

**Comment by karissawhiting** [comment]
@michaelcurry1123 I think that would work for sorting, but at the end we need to end up with two columns with hugo 1 and hugo 2 so need to keep the correct portions of gene string together for that I think?

**Comment by hfuchs5** [comment]
@karissawhiting @michaelcurry1123 yeah, "ax-ng" would have to be paired together because -ng is a suffix to ax, not a third gene name. I haven't seen any cases that are three genes fused together.

**Comment by michaelcurry1123** [comment]
In separate you can set remove = FALSE , which you have in one of your separate function calls but I think if you do it in both then you can use the original column you separated to put into two columns. But I don't know all the use cases and if this is too generous with my assumptions I will quit pestering! I just there was a lot of code dedicated to adding the _ and was seeing if you can get around that and don't need to maintain it.

**Comment by karissawhiting** [comment]
@michaelcurry1123 I _think_ you would still need to know where the suffix goes? like:

```
fusions
BRAF-ERCC4-AS1
ERCC4-AS1-BRAF
```

becomes
```
AS1-BRAF-ERCC4 
AS1-BRAF-ERCC4 
```

for deduplicating (which is fine). But then we want to split into two columns using the original `fusions` column we would get the following options:

```
Hugo 1          Hugo2
BRAF            ERCC4-AS1
ERCC4           AS1-BRAF
```

How would we know which is correct? In that case the first one is correct with ERCC4-AS1. 

We could potentially match back to the original `hugo_symbol` column here but that may be more complicated and also sometimes the `hugo_symbol` column uses a different alias and gene names won't match :/

**Comment by michaelcurry1123** [comment]
ah ok! makes sense

**Pull request merged**
