### PR TITLE
Hf hackathon

### PR DESCRIPTION
**Pull request by hfuchs5**
**What changes are proposed in this pull request?**
Added .recode_cna_alterations internal function, unit tests, and applied it throughout the package.

**If there is an GitHub issue associated with this pull request, please provide link.**
#178 & #177

--------------------------------------------------------------------------------

  Reviewer Checklist (if item does not apply, mark is as complete)

- [] PR branch has pulled the most recent updates from main branch. Ensure the pull request branch and your local version match and both have the latest updates from the main branch.
- [] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site()`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true"), covr::report())`. Begin in a fresh R session without any packages loaded.
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
 - [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cbioportalR (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR

### CODE REVIEW

**Comment by karissawhiting** [comment]
This looks great @hfuchs5 !

I think I'm going to move the code below back into the main .cna_gene_binary so all data checking for CNA specific stuff in done there and the new function is recoding functionality only

```r 


  if(!("alteration" %in% colnames(cna))) {
    cli::cli_abort("An alteration column is missing from your cna data. Use pivot_cna_longer(),
                   which will recode alterations, instead if dataset is in API format.")
  }

  # Make sure hugo & alteration is character
  cna <- cna %>%
    mutate(hugo_symbol = as.character(.data$hugo_symbol)) %>%
    mutate(alteration = tolower(str_trim(as.character(.data$alteration))))

```

**Comment by michaelcurry1123** [comment]
code snippet to work on for me: 

```
mut2 <- mutations %>%  
        filter(sampleId %in% samples2) %>% 
        group_by(sampleId,hugoGeneSymbol) %>% 
        filter(row_number()==1) %>% 
        mutate(fl = 1) %>% 
        pivot_wider(id_cols = sampleId, names_from = hugoGeneSymbol, values_from  = fl,
                    values_fill = 0) %>% 

        ungroup() %>% 
        select(-sampleId)

class(mut2) <- "data.frame"

row.names(mut2) <- samples
```

**Comment by michaelcurry1123** [comment]
@karissawhiting @hfuchs5 
Hi all I am reworking .genbin_matrix so that it can be written in fewer lines of code. Here is my working example that I am going to use

```
.genbin_matrix <- function(data, 
         samples,
         type = c("mut", "cna", "fus"),
         delamp = "mut_fus"){
  
  if(type == "mut"){
    names_glue = rlang::expr(NULL)
  }else if(type == "cna" & delamp == "deletion"){
    names_glue = rlang::expr("{hugo_symbol}.Del")
  }else if( type == "cna" & delamp == "amplification"){
    names_glue = rlang::expr("{hugo_symbol}.Amp")
  }else{
    names_glue = rlang::expr("{hugo_symbol}.fus")
  }
  
   data %>%
    filter(.data$sample_id %in% samples) %>%
    {if(type == "cna" & delamp == "deletion") filter(.,alteration %in% c("deletion","homozygous deletion")) else 
      if(type == "cna" & delamp == "amplification")
      filter(., alteration %in% c("amplification","high level amplification") ) else(select(., everything()))} %>% 
    group_by(.data$sample_id,.data$hugo_symbol) %>%
    filter(row_number()==1) %>%
    mutate(fl = 1) %>%
    pivot_wider(id_cols = "sample_id", names_from = "hugo_symbol", values_from  = "fl",
                values_fill = 0, names_glue = rlang::eval_tidy( names_glue) ) %>%
    ungroup() 
}

```

This dplyr solution is faster than the Axel/Arishi version and (hopefully) a bit more readable. Working on integrating this into this current branch

**Comment by michaelcurry1123** [comment]
I added my changes to my local branch but there are merge conflicts with main, if we have time tomorrow I would like to discuss these changes , note discuss NAs in del and amp

**Pull request merged**
